  CinderVolumeTypes.create_and_list_encryption_type:
    -
      args:
        specs:
          provider: "LuksEncryptor"
          cipher: "aes-xts-plain64"
          key_size: 512
          control_location: "front-end"
      runner:
        type: "constant"
        times: 4
        concurrency: 2
      context:
        users:
          tenants: 2
          users_per_tenant: 2
      sla:
        failure_rate:
          max: 0
